name: hex7

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  deploy_hex7:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v2

      - name: Setting export variables values
        run: |
          pwd
          ls -la
          env
          TIMEZONE=EST5EDT
          APP_VERSION=$(cat VERSION)
          S3_PUBLIC_BUCKET=hex7.com
          AWS_REGION=us-east-1
          echo "TZ=${TIMEZONE}"
          echo "APP_VERSION=${APP_VERSION}"
          echo "S3_PUBLIC_BUCKET=${S3_PUBLIC_BUCKET}"
          echo "AWS_REGION=${AWS_REGION}"
          echo "TZ=${TIMEZONE}" >> $GITHUB_ENV
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV
          echo "S3_PUBLIC_BUCKET=${S3_PUBLIC_BUCKET}" >> $GITHUB_ENV
          echo "AWS_REGION=${AWS_REGION}" >> $GITHUB_ENV


      - name: prepare hex7 workspace
        run: |
          echo prepare workspace
          pwd
          rm -fv deploy/index.html
          touch deploy/index.html
          ls -la deploy/


      - name: init hex7 terraform
        run: |
          pwd
          terraform init
        working-directory: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.S3_USER }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
          TF_VAR_app_version: ${{ env.APP_VERSION }}
          TF_INPUT: false


      - name: run hex7 terraform
        run: |
          pwd
          terraform apply --auto-approve
        working-directory: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
          TF_VAR_app_version: ${{ env.APP_VERSION }}
          TF_INPUT: false


      - name: test hex7 sites
        run: |
          echo
          echo hex7.net
          echo
          echo testing http://hex7.net
          curl http://hex7.net
          echo testing https://hex7.net
          curl https://hex7.net
          echo
          echo www.hex7.net
          echo
          echo testing http://www.hex7.net
          curl http://www.hex7.net
          echo testing https://www.hex7.net
          curl https://www.hex7.net
          echo
          echo hex7.com
          echo
          echo testing http://hex7.com
          curl http://hex7.com
          echo testing https://hex7.com
          curl https://hex7.com
          echo
          echo www.hex7.com
          echo
          echo testing http://www.hex7.com
          curl http://www.hex7.com
          echo testing https://www.hex7.com
          curl https://www.hex7.com
          echo
          echo
          echo success
